name: Docs

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  merge_group:

permissions:
  contents: read

jobs:
  Docs:
    permissions:
      contents: read
    uses: tskit-dev/.github/.github/workflows/docs.yml@v20
    with:
      install-playwright: true
